/**
 * Stable CSS variable names for Matcha tokens.
 * Primitives use `--matcha-*`; theme utilities use the same names as Tailwind (e.g. `--spacing-tight`).
 */
export const cssVar = {
  color: {
    background: "var(--background)",
    foreground: "var(--foreground)",
    card: "var(--card)",
    cardForeground: "var(--card-foreground)",
    popover: "var(--popover)",
    popoverForeground: "var(--popover-foreground)",
    primary: "var(--primary)",
    primaryForeground: "var(--primary-foreground)",
    secondary: "var(--secondary)",
    secondaryForeground: "var(--secondary-foreground)",
    muted: "var(--muted)",
    mutedForeground: "var(--muted-foreground)",
    accent: "var(--accent)",
    accentForeground: "var(--accent-foreground)",
    destructive: "var(--destructive)",
    destructiveForeground: "var(--destructive-foreground)",
    border: "var(--border)",
    input: "var(--input)",
    ring: "var(--ring)",
    chart1: "var(--chart-1)",
    chart2: "var(--chart-2)",
    chart3: "var(--chart-3)",
    chart4: "var(--chart-4)",
    chart5: "var(--chart-5)",
    success: "var(--success)",
    successForeground: "var(--success-foreground)",
    successMuted: "var(--success-muted)",
    warning: "var(--warning)",
    warningForeground: "var(--warning-foreground)",
    warningMuted: "var(--warning-muted)",
    info: "var(--info)",
    infoForeground: "var(--info-foreground)",
    infoMuted: "var(--info-muted)",
  },
  /** Raw radius primitives (always resolve) */
  radiusPrimitive: {
    xs: "var(--matcha-radius-xs)",
    "2xl": "var(--matcha-radius-2xl)",
    "3xl": "var(--matcha-radius-3xl)",
    full: "var(--matcha-radius-full)",
    base: "var(--radius)",
  },
  /** Theme-backed (same as Tailwind rounded-*) */
  radius: {
    xs: "var(--matcha-radius-xs)",
    sm: "calc(var(--radius) - 4px)",
    md: "calc(var(--radius) - 2px)",
    lg: "var(--radius)",
    xl: "calc(var(--radius) + 4px)",
    "2xl": "var(--matcha-radius-2xl)",
    "3xl": "var(--matcha-radius-3xl)",
    "4xl": "calc(var(--radius) + 12px)",
    full: "var(--matcha-radius-full)",
    base: "var(--radius)",
  },
  /** Raw spacing primitives */
  spacingPrimitive: {
    tight: "var(--matcha-space-tight)",
    snug: "var(--matcha-space-snug)",
    comfortable: "var(--matcha-space-comfortable)",
    relaxed: "var(--matcha-space-relaxed)",
    loose: "var(--matcha-space-loose)",
    gutter: "var(--matcha-space-gutter)",
    section: "var(--matcha-space-section)",
    page: "var(--matcha-space-page)",
  },
  spacing: {
    tight: "var(--matcha-space-tight)",
    snug: "var(--matcha-space-snug)",
    comfortable: "var(--matcha-space-comfortable)",
    relaxed: "var(--matcha-space-relaxed)",
    loose: "var(--matcha-space-loose)",
    gutter: "var(--matcha-space-gutter)",
    section: "var(--matcha-space-section)",
    page: "var(--matcha-space-page)",
  },
  font: {
    sans: "var(--font-sans-stack)",
    mono: "var(--font-mono-stack)",
  },
} as const;
